### ISSUE TITLE
project won't compile

### ISSUE THREAD

**Issue by mclaugsf** [gnetsanet/aws_glue_workflow_relationalize#1]
please help - here is my issue:

<pre>
(base) aws_glue_workflow_relationalize % make
make: *** No targets specified and no makefile found.  Stop.
</pre>

is there a yml bug?

**Comment by mclaugsf** [comment]
nevermind - i was just joking around.

**Comment by gnetsanet** [comment]
👍🏾  You may need to create a Redshift cluster first, that way the Glue workflow and ETL job inside builds the data lake for you. :-)
